import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { getCurrentUser } from "@/lib/actions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();


  return (
    <html lang="en">
      <body className="flex flex-col items-center min-h-screen bg-gray-100">
        <Header user={user} />
        <main className="w-full max-w-360 flex-1 px-6 py-12">{children}</main>
      </body>
    </html>
  );
}
