import type { Metadata } from "next";
import "../(main)/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center min-h-screen bg-gray-200">
        <main className="w-full max-w-360 flex-1 px-6 py-12 flex items-center justify-center">{children}</main>
      </body>
    </html>
  );
}
