import type { Metadata } from "next";
import "../globals.css"
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <AuthProvider>
          <Toaster position="bottom-right" />
          <main className="flex min-h-screen items-center justify-center p-4">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
