import type { Metadata } from "next";
import "../globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthContext";
import { getCurrentUser } from "../(main)/posts/serverActions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authUser = await getCurrentUser();

  return (
    <html lang="en">
      <body>
        <AuthProvider initialUser={authUser}>
          <Toaster position="bottom-right" />
          <main className="flex min-h-screen items-center justify-center p-4">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
