import type { Metadata } from "next";
import "../globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <AuthProvider>
          <Toaster position="bottom-right" />
          <Navbar />
          <main className="flex-1 w-full flex justify-center">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
